### ISSUE TITLE
您好想请教问题

### ISSUE THREAD

**Issue by hkzzzzzz** [ek2061/hsipl_tools#1]
请问您在波段选择中提到的方法有具体的论文吗，谢谢

**Comment by ek2061** [comment]
您好，

CEM-BCC / CEM-BCM / CEM-BDM 可以參考 [Constrained band selection for hyperspectral imagery](https://ieeexplore.ieee.org/document/1634721)  

MinV-BP / MaxV-BP / CTBS 可以參考 [Constrained-Target Band Selection for Multiple-Target Detection](https://ieeexplore.ieee.org/document/8686257)  

TCIMBS 可以參考 [Target-Constrained Interference-Minimized Band Selection for Hyperspectral Target Detection](https://ieeexplore.ieee.org/document/9178496)  

部分演算法參考太老師撰寫的這本書
Chein-I Chang, Hyperspectral Data Processing: Algorithm Design and Analysis, John Wiley and Sons, 2013

**Comment by hkzzzzzz** [comment]
> 您好，
> 
> CEM-BCC / CEM-BCM / CEM-BDM 可以參考 [Constrained band selection for hyperspectral imagery](https://ieeexplore.ieee.org/document/1634721)
> 
> MinV-BP / MaxV-BP / CTBS 可以參考 [Constrained-Target Band Selection for Multiple-Target Detection](https://ieeexplore.ieee.org/document/8686257)
> 
> TCIMBS 可以參考 [Target-Constrained Interference-Minimized Band Selection for Hyperspectral Target Detection](https://ieeexplore.ieee.org/document/9178496)
> 
> 部分演算法參考太老師撰寫的這本書
> Chein-I Chang, Hyperspectral Data Processing: Algorithm Design and Analysis, John Wiley and Sons, 2013

万分感谢
